rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 6, i: 2.5, d: 4.5}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 60, i: 10.0, d: 20.0} 

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 50, i: 10.0, d: 20.0}
    
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 5, i: 0.5, d: 2.5}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 5, i: 0.5, d: 2.5}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 4, i: 0.5, d: 1.5}
 